name: Run test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install Dep
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: yarn dev

      - name: Debug
        run: cat /etc/hosts

      - name: Run tests 
        run: npx cypress run --config-file=cypress.config.ts


